######################################################################
# CONSTANTS FILES
######################################################################

# The constants below should drive initial values and constants for all ptv commands

# MAX PARTICLES TO ALLOW IN A FIELD (currently on track)
MAXPARTICLES = 10000
PARTICLE_STRICT=False

# MAXIMUM ITERATIONS FOR RM MATCHING
RM_MAX_ITER = 100

# SMALL PARAMETER FOR RM MATCHING
RM_EPSILON= 1e-3

# SMALL PARAMETER TO AVOID INFS IN DIVISION
EPSILON= 1e-3

# minimum SNR
SNRVALUE = 1

# boundaries for particle detections
PARTICLE_CROP = 1
PARTICLE_THRESHOLD = 0
PARTICLE_RADIUS = 3
# VALUE FOR GAUSSIAN FOR LOW PASS
PARTICLE_LOWPASS = 1.2
# VALUE FOR MAX/MIN HIGH PASS FILTER
PARTICLE_HIGHPASS = 0
PARTICLE_CENTROID_METHOD = '3pt'
PARTICLE_PEAK_METHOD = 'strict'
PARTICLE_LSQ_BOUNDS = 3

RM_TM = 6
RM_TN = 6
RM_TQ = 3

RM_MATCH_THRESHOLD = 0.8
RM_DEFAULT_METHOD='CCRM'

# PTVCC MINIMUM SNR REQUIREMENT
CC_PTVSNR=1

# SIZE OF INTERROGATION WINDOW FOR CC
CC_INTERROGATIONWINDOWSIZE = 12

# MAXIMUM NUMBER OF TRACKS
MAXTRACKS = 100000

# THE MAXIMUM NUMBER OF POTENTIAL MATCHES TO CONSIDER FOR 4BE
MAXFRIENDS = 1000

# REF FILE
REF_FILE = 'None'

